font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Light
bold_font        family='JetBrainsMonoNL Nerd Font Mono' style=Bold
italic_font      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-LightItalic
bold_italic_font family='JetBrainsMonoNL Nerd Font Mono' style='Bold Italic'

font_size 12.5

window_padding_width 2 4

placement_strategy top-left
enabled_layouts splits

tab_bar_style slant
tab_bar_edge top

allow_remote_control socket-only

macos_option_as_alt right

scrollback_pager nvim '+set filetype=kitty' -R

macos_colorspace default
macos_quit_when_last_window_closed yes

scrollback_pager_history_size 100

dim_opacity 0.7

cursor_trail 1
cursor_trail_decay 0.3 0.3
cursor_trail_start_threshold 0
custom_shaders cursor-glow fade-inactive
