words = [
    "andymass",
    "bufnr",
    "cmdline",
    "diffview",
    "emmylua",
    "eob",
    "fff's",
    "fillchars",
    "folke",
    "keymaps",
    "laststatus",
    "lazydev",
    "lnum",
    "lspconfig",
    "matchparen",
    "nvim's",
    "saghen",
    "sindrets",
    "sourcekit",
    "stevearc",
    "tpope",
]
