vim.loader.enable()

require('user.config.options')
-- require('user.config.mini')
require('user.config.lazy')
require('user.config.colorscheme')
require('user.config.filetypes')
require('user.config.keymaps')
require('user.config.autocommands')
require('user.config.lsp')
require('user.config.neovide')
require('user.config.tig')
