words = [
    "CLI",
    "Geofence",
    "Pii",
    "aab",
    "aapl",
    "aborter",
    "abv",
    "agentic",
    "altool",
    "atlassian",
    "autocmd",
    "avd",
    "backpressure",
    "bigrig",
    "bikeshed",
    "caffeinate",
    "chargebee",
    "cheatham",
    "checkboxes",
    "checkmark",
    "clicolor",
    "cloudflare",
    "csharpier",
    "cwd",
    "deepseek",
    "deno",
    "devicectl",
    "direnv",
    "domcontentloaded",
    "drilldown",
    "dto",
    "dtos",
    "eaddrinuse",
    "earendil",
    "eas",
    "entra",
    "esc",
    "etf",
    "eza",
    "favourite",
    "favourites",
    "formatters",
    "frecency",
    "frontmatter",
    "fzf",
    "garmin",
    "ghostty",
    "gpt",
    "gpt's",
    "graphiti",
    "gunzip",
    "hammerspoon",
    "hass",
    "hexdump",
    "homeassistant",
    "homebrew",
    "hono",
    "hsl",
    "immer",
    "iphonesimulator",
    "issuances",
    "javac",
    "jsdom",
    "kinesis",
    "kysely",
    "latexindent",
    "lauderdale",
    "launchctl",
    "launchd",
    "lazygit",
    "leaderboard",
    "leaderboards",
    "lifecycle",
    "linters",
    "llc",
    "llm",
    "logstream",
    "lookups",
    "lucide",
    "makedir",
    "mcp",
    "mins",
    "mise",
    "mkdir",
    "moneyscope",
    "mvn",
    "natively",
    "neovide",
    "neovim",
    "nestjs",
    "nvim",
    "nyt",
    "octo",
    "oneline",
    "openai",
    "opencode",
    "osascript",
    "osc",
    "ota",
    "oxfmt",
    "oxlint",
    "pangrams",
    "pgrep",
    "pkill",
    "plists",
    "pnpm",
    "podspec",
    "profiler",
    "programmatically",
    "pullthru",
    "qall",
    "rdbms",
    "readlink",
    "realpath",
    "reduxjs",
    "ripgrep",
    "rudderstack",
    "rustup",
    "rxvt",
    "sed",
    "segoe",
    "selenized",
    "sendable",
    "setuid",
    "simctl",
    "sns",
    "sqs",
    "strawman",
    "strikethrough",
    "stylua",
    "subagents",
    "subcomponents",
    "subentries",
    "substack",
    "tappable",
    "terminfo",
    "tig",
    "tsgo",
    "typebox",
    "udid",
    "undercurl",
    "unfocus",
    "updateable",
    "utc",
    "vin",
    "vip",
    "vitest",
    "wavebox",
    "wez",
    "wezterm",
    "whoami",
    "worktree",
    "wsl",
    "wss",
    "xcconfig",
    "xclip",
    "xcodebuild",
    "xcodeproj",
    "xcrun",
    "xcworkspace",
    "xdg",
    "xvf",
    "zipcode",
    "zod",
    "zoxide",
    "zstd",
    "zuban",
]
