[[mgr.prepend_keymap]]
on = "q"
run = "quit --no-cwd-file"
desc = "Quit"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit"
desc = "Quit, possibly changing CWD"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin nvim"
desc = "Open the file in nvim if yazi was started by nvim"
