[mgr]
ratio = [0, 4, 4]

[preview]
max_width = 2000
max_height = 2000

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[opener.nvim]]
run = """/opt/homebrew/bin/nvim \
	--server "${NVIM_SERVER}" \
	--remote-expr "v:lua.vim.cmd.edit('$@')""""
block = false
desc = "Edit in Neovim"
