[mgr]
ratio = [0, 4, 4]

[preview]
max_width = 2000
max_height = 2000

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
