[metadata]
name = 'Catppuccin Latte (catppuccin)'

[colors]
ansi = [
	'#5c5f77',
	'#d20f39',
	'#40a02b',
	'#df8e1d',
	'#1e66f5',
	'#ea76cb',
	'#179299',
	'#acb0be',
]
background = '#eff1f5'
brights = [
	'#6c6f85',
	'#d20f39',
	'#40a02b',
	'#df8e1d',
	'#1e66f5',
	'#ea76cb',
	'#179299',
	'#bcc0cc',
]
compose_cursor = '#dd7878'
cursor_border = '#dc8a78'
foreground = '#4c4f69'
scrollbar_thumb = '#acb0be'
selection_bg = '#acb0be'
selection_fg = '#4c4f69'
split = '#9ca0b0'
visual_bell = '#ccd0da'

[colors.indexed]
16 = '#fe640b'
17 = '#dc8a78'
18 = '#8839ef'
19 = '#7287fd'

[colors.tab_bar]
background = '#bcc0cc'

[colors.tab_bar.active_tab]
bg_color = '#eff1f5'
fg_color = '#4c4f69'

[colors.tab_bar.inactive_tab]
bg_color = '#ccd0da'
fg_color = '#5c5f77'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eff1f5'
fg_color = '#4c4f69'

[colors.tab_bar.new_tab]
bg_color = '#bcc0cc'
fg_color = '#bcc0cc'

[colors.tab_bar.new_tab_hover]
bg_color = '#bcc0cc'
fg_color = '#4c4f69'
