[metadata]
name = 'Catppuccin Macchiato (catppuccin)'

[colors]
ansi = [
  '#494d64',
  '#ed8796',
  '#a6da95',
  '#eed49f',
  '#8aadf4',
  '#f5bde6',
  '#8bd5ca',
  '#b8c0e0',
]
background = '#24273a'
brights = [
  '#5b6078',
  '#ed8796',
  '#a6da95',
  '#eed49f',
  '#8aadf4',
  '#f5bde6',
  '#8bd5ca',
  '#a5adcb',
]
compose_cursor = '#f0c6c6'
cursor_border = '#f4dbd6'
foreground = '#cad3f5'
scrollbar_thumb = '#5b6078'
selection_bg = '#5b6078'
selection_fg = '#cad3f5'
split = '#6e738d'
visual_bell = '#363a4f'

[colors.indexed]
16 = '#f5a97f'
17 = '#f4dbd6'
18 = '#c6a0f6'
19 = '#b7bdf8'

[colors.tab_bar]
background = '#474d64'

[colors.tab_bar.active_tab]
bg_color = '#24273a'
fg_color = '#cad3f5'

[colors.tab_bar.inactive_tab]
bg_color = '#363a4f'
fg_color = '#a5adcb'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#24273a'
fg_color = '#cad3f5'

[colors.tab_bar.new_tab]
bg_color = '#474d64'
fg_color = '#474d64'

[colors.tab_bar.new_tab_hover]
bg_color = '#494d64'
fg_color = '#cad3f5'
