[metadata]
name = 'Catppuccin Frappe (catppuccin)'

[colors]
ansi = [
  '#51576d',
  '#e78284',
  '#a6d189',
  '#e5c890',
  '#8caaee',
  '#f4b8e4',
  '#81c8be',
  '#b5bfe2',
]
background = '#303446'
brights = [
  '#626880',
  '#e78284',
  '#a6d189',
  '#e5c890',
  '#8caaee',
  '#f4b8e4',
  '#81c8be',
  '#a5adce',
]
compose_cursor = '#eebebe'
cursor_border = '#f2d5cf'
foreground = '#c6d0f5'
scrollbar_thumb = '#626880'
selection_bg = '#626880'
selection_fg = '#c6d0f5'
split = '#737994'
visual_bell = '#414559'

[colors.indexed]
16 = '#ef9f76'
17 = '#f2d5cf'
18 = '#ca9ee6'
19 = '#babbf1'

[colors.tab_bar]
background = '#51576d'

[colors.tab_bar.active_tab]
bg_color = '#303446'
fg_color = '#c6d0f5'

[colors.tab_bar.inactive_tab]
bg_color = '#414559'
fg_color = '#a5adce'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#303446'
fg_color = '#c6d0f5'

[colors.tab_bar.new_tab]
bg_color = '#51576d'
fg_color = '#51576d'

[colors.tab_bar.new_tab_hover]
bg_color = '#51576d'
fg_color = '#c6d0f5'
